In [ ]:
### element accessing row/columns
#loc iloc-->location and index location based

In [17]:
import pandas as pd
df=pd.DataFrame({"name":['pinky','pop','push','puppy'],"roll-numbers":[401,402,403,405],"branch":["cse","ece","civil","eee"]})
df

name  roll-numbers branch
0  pinky           401    cse
1    pop           402    ece
2   push           403  civil
3  puppy           405    eee

In [18]:
df.loc[1]

name            pop
roll-numbers    402
branch          ece
Name: 1, dtype: object

In [19]:
df.iloc[2]['roll-numbers']

403

In [20]:
df.iloc[0]

name            pinky
roll-numbers      401
branch            cse
Name: 0, dtype: object

In [21]:
df.iloc[3]

name            puppy
roll-numbers      405
branch            eee
Name: 3, dtype: object

In [22]:
df.iloc[2]["branch"]

'civil'

In [23]:
df.describe()

roll-numbers
count      4.000000
mean     402.750000
std        1.707825
min      401.000000
25%      401.750000
50%      402.500000
75%      403.500000
max      405.000000

In [24]:

df.count()

name            4
roll-numbers    4
branch          4
dtype: int64

In [25]:
df.dtypes

name            object
roll-numbers     int64
branch          object
dtype: object

In [26]:
df.count(axis='rows')

name            4
roll-numbers    4
branch          4
dtype: int64

In [27]:
df

name  roll-numbers branch
0  pinky           401    cse
1    pop           402    ece
2   push           403  civil
3  puppy           405    eee

In [29]:
df.set_index(["roll-numbers"])

name branch
roll-numbers              
401           pinky    cse
402             pop    ece
403            push  civil
405           puppy    eee

In [31]:
df.set_index(["roll-numbers","branch"])

name
roll-numbers branch       
401          cse     pinky
402          ece       pop
403          civil    push
405          eee     puppy

### creating a series dataframe

In [34]:
import numpy as np
frame=pd.Series([1,2,3,4,5])
frame

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [35]:
frame.isnull()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [36]:
frame.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [37]:
frame.count()

5

In [39]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [41]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
x.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [44]:
data=pd.DataFrame(np.arange(12))

In [45]:
data

0
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11

In [50]:
data=pd.DataFrame(np.arange(12).reshape(4,3))

In [51]:
data

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [53]:
data=pd.DataFrame(np.arange(12).reshape(4,3),columns=list('xyz'))

In [54]:
data

x   y   z
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [55]:
data

x   y   z
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [56]:
d=pd.DataFrame(np.arange(20).reshape(4,5))

In [57]:
d

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [58]:
d=pd.DataFrame(np.arange(20).reshape(4,5),columns=list('abcde'))

In [59]:
d

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [62]:
d.loc[1,'c']=np.nan

In [63]:
d

a   b     c   d   e
0   0   1   2.0   3   4
1   5   6   NaN   8   9
2  10  11  12.0  13  14
3  15  16  17.0  18  19

In [65]:
d.isnull().sum()

a    0
b    0
c    1
d    0
e    0
dtype: int64

In [66]:
df

name  roll-numbers branch
0  pinky           401    cse
1    pop           402    ece
2   push           403  civil
3  puppy           405    eee

In [69]:
df+d

a   b branch   c   d   e name  roll-numbers
0 NaN NaN    NaN NaN NaN NaN  NaN           NaN
1 NaN NaN    NaN NaN NaN NaN  NaN           NaN
2 NaN NaN    NaN NaN NaN NaN  NaN           NaN
3 NaN NaN    NaN NaN NaN NaN  NaN           NaN

In [72]:
c=df.add(data)
c

branch name  roll-numbers   x   y   z
0    NaN  NaN           NaN NaN NaN NaN
1    NaN  NaN           NaN NaN NaN NaN
2    NaN  NaN           NaN NaN NaN NaN
3    NaN  NaN           NaN NaN NaN NaN

In [77]:
c.add(data,fill_value=9)

branch name  roll-numbers     x     y     z
0    NaN  NaN           NaN   9.0  10.0  11.0
1    NaN  NaN           NaN  12.0  13.0  14.0
2    NaN  NaN           NaN  15.0  16.0  17.0
3    NaN  NaN           NaN  18.0  19.0  20.0

### creating random values (numpy)

In [78]:
np.random.randn

<function RandomState.randn>

In [79]:
np.random.randn(2,5)

array([[-1.98838691,  0.56308431, -0.02729856, -0.1867179 , -0.06996677],
       [-0.52586377,  0.69403747, -1.86248865, -1.67985907,  0.07235238]])

In [80]:
np.random.rand(1,10)

array([[0.67041599, 0.44004555, 0.82997441, 0.19209154, 0.87960837,
        0.36468015, 0.60287161, 0.54754996, 0.2671312 , 0.07775573]])

### creating dataframe with random values

In [81]:
k=pd.DataFrame(np.random.randn(2,6))
k

0         1         2         3         4         5
0 -0.097247  0.047596  0.197333  0.805587 -0.750487  0.405967
1 -1.217001 -0.636557 -1.558470  0.238556  0.589969  0.161122

In [84]:
k=pd.DataFrame(np.random.randn(2,6),index=['x','y'])
k

0         1         2         3         4         5
x  1.035023 -0.796802 -0.482763 -0.572319  2.308904 -0.078199
y  0.062595  0.509086 -0.037518 -0.381987  1.989740 -1.131542

In [87]:
k=pd.DataFrame(np.random.randn(2,6),columns=['a','b','c','d','e','f'])
k

a         b         c         d         e         f
0 -1.200594  0.658828 -0.976854  1.129336 -0.090096  0.812170
1  1.252383  0.235138 -0.033699  0.068371  0.852534 -1.925515

In [88]:
k.index=['a','b']
k

a         b         c         d         e         f
a -1.200594  0.658828 -0.976854  1.129336 -0.090096  0.812170
b  1.252383  0.235138 -0.033699  0.068371  0.852534 -1.925515

In [89]:
k.columns=['x','y','z','l','m','n']
k

x         y         z         l         m         n
a -1.200594  0.658828 -0.976854  1.129336 -0.090096  0.812170
b  1.252383  0.235138 -0.033699  0.068371  0.852534 -1.925515

In [94]:
## reindexing
k1=k.reindex(['b','a'])
k1

x         y         z         l         m         n
b  1.252383  0.235138 -0.033699  0.068371  0.852534 -1.925515
a -1.200594  0.658828 -0.976854  1.129336 -0.090096  0.812170

In [96]:
k1.isnull().sum()

x    0
y    0
z    0
l    0
m    0
n    0
dtype: int64

In [97]:
## dropping the null values
k1.dropna()

x         y         z         l         m         n
b  1.252383  0.235138 -0.033699  0.068371  0.852534 -1.925515
a -1.200594  0.658828 -0.976854  1.129336 -0.090096  0.812170

In [98]:
## fill the null values
k1.fillna(3)

x         y         z         l         m         n
b  1.252383  0.235138 -0.033699  0.068371  0.852534 -1.925515
a -1.200594  0.658828 -0.976854  1.129336 -0.090096  0.812170

In [99]:
k1.fillna(method='ffill',axis=0).fillna(1)   ## forword fill
k1

x         y         z         l         m         n
b  1.252383  0.235138 -0.033699  0.068371  0.852534 -1.925515
a -1.200594  0.658828 -0.976854  1.129336 -0.090096  0.812170

In [100]:
k1.fillna(method='bfill',axis=0).fillna(2)        ## fill backword
k1

x         y         z         l         m         n
b  1.252383  0.235138 -0.033699  0.068371  0.852534 -1.925515
a -1.200594  0.658828 -0.976854  1.129336 -0.090096  0.812170

In [101]:
k1.isna()

x      y      z      l      m      n
b  False  False  False  False  False  False
a  False  False  False  False  False  False

In [108]:
pd.isna(k1['y'])


b    False
a    False
Name: y, dtype: bool

### data replacing

In [109]:
k1

x         y         z         l         m         n
b  1.252383  0.235138 -0.033699  0.068371  0.852534 -1.925515
a -1.200594  0.658828 -0.976854  1.129336 -0.090096  0.812170

In [113]:
s=pd.DataFrame({'x':[1,2,3,5,6],'y':[4,5,6,7,8,],'z':[2,5,6,8,9]})
s

x  y  z
0  1  4  2
1  2  5  5
2  3  6  6
3  5  7  8
4  6  8  9

In [114]:
s.replace(4,55)

x   y  z
0  1  55  2
1  2   5  5
2  3   6  6
3  5   7  8
4  6   8  9

In [118]:
s.replace([2,5],[66,77])

x   y   z
0   1   4  66
1  66  77  77
2   3   6   6
3  77   7   8
4   6   8   9

In [ ]:
s.replace[{0,1,}]

### sorting and reindexing

In [116]:
s.sort_index()

x  y  z
0  1  4  2
1  2  5  5
2  3  6  6
3  5  7  8
4  6  8  9

In [117]:
s.sort_index(axis=1)

x  y  z
0  1  4  2
1  2  5  5
2  3  6  6
3  5  7  8
4  6  8  9

## groupby

In [119]:
animal=pd.DataFrame({'name':['dog','cat','cow','dog','cow'],'place':['zoo','jungle','zoo','jungle','zoo'],'features':['a','b','c','a','b']})


In [120]:
animal

name   place features
0  dog     zoo        a
1  cat  jungle        b
2  cow     zoo        c
3  dog  jungle        a
4  cow     zoo        b

In [122]:
animal.groupby('name').sum()

place features
name                    
cat      jungle        b
cow      zoozoo       cb
dog   zoojungle       aa

In [125]:
animal.groupby('features').count()

name  place
features             
a            2      2
b            2      2
c            1      1

In [126]:
animal.groupby('features').sum()

name      place
features                   
a         dogdog  zoojungle
b         catcow  junglezoo
c            cow        zoo

## Ranking

In [142]:
animal=pd.DataFrame({'name':['dog','cat','cow','dog','cow'],'place':['zoo','jungle','zoo','jungle','zoo'],'legs':[4,4,2,2,np.nan]})

In [143]:
animal

name   place  legs
0  dog     zoo   4.0
1  cat  jungle   4.0
2  cow     zoo   2.0
3  dog  jungle   2.0
4  cow     zoo   NaN

In [144]:
animal["ranks"]=animal['legs'].rank()

In [145]:
animal

name   place  legs  ranks
0  dog     zoo   4.0    3.5
1  cat  jungle   4.0    3.5
2  cow     zoo   2.0    1.5
3  dog  jungle   2.0    1.5
4  cow     zoo   NaN    NaN

In [146]:
animal["max_rank"]=animal["legs"].rank(method="max")
animal

name   place  legs  ranks  max_rank
0  dog     zoo   4.0    3.5       4.0
1  cat  jungle   4.0    3.5       4.0
2  cow     zoo   2.0    1.5       2.0
3  dog  jungle   2.0    1.5       2.0
4  cow     zoo   NaN    NaN       NaN

In [147]:
animal["first_rank"]=animal["legs"].rank(method="first")
animal

name   place  legs  ranks  max_rank  first_rank
0  dog     zoo   4.0    3.5       4.0         3.0
1  cat  jungle   4.0    3.5       4.0         4.0
2  cow     zoo   2.0    1.5       2.0         1.0
3  dog  jungle   2.0    1.5       2.0         2.0
4  cow     zoo   NaN    NaN       NaN         NaN

In [148]:
animal["non_rank"]=animal['legs'].rank(na_option="bottom")
animal

name   place  legs  ranks  max_rank  first_rank  non_rank
0  dog     zoo   4.0    3.5       4.0         3.0       3.5
1  cat  jungle   4.0    3.5       4.0         4.0       3.5
2  cow     zoo   2.0    1.5       2.0         1.0       1.5
3  dog  jungle   2.0    1.5       2.0         2.0       1.5
4  cow     zoo   NaN    NaN       NaN         NaN       5.0

In [149]:
animal["pct_rank"]=animal['legs'].rank(pct="true")
animal

name   place  legs  ranks  max_rank  first_rank  non_rank  pct_rank
0  dog     zoo   4.0    3.5       4.0         3.0       3.5     0.875
1  cat  jungle   4.0    3.5       4.0         4.0       3.5     0.875
2  cow     zoo   2.0    1.5       2.0         1.0       1.5     0.375
3  dog  jungle   2.0    1.5       2.0         2.0       1.5     0.375
4  cow     zoo   NaN    NaN       NaN         NaN       5.0       NaN

## categorise

In [150]:
m_Frame=pd.DataFrame({'x':[1,2,3,4,5],'y':[6,7,8,9,10]})
m_Frame

x   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [152]:
m_Frame["cc"]=m_Frame['y'].astype('category')
m_Frame

x   y  cc
0  1   6   6
1  2   7   7
2  3   8   8
3  4   9   9
4  5  10  10

In [155]:
m_Frame["cc"].cat.categories=["gud","bad","worst","poor","vbad"]
m_Frame

x   y     cc
0  1   6    gud
1  2   7    bad
2  3   8  worst
3  4   9   poor
4  5  10   vbad

In [156]:
m_Frame["cc"]=m_Frame["cc"].set_categories=["gud","bad","avg","aavg","vbad"]
m_Frame

x   y    cc
0  1   6   gud
1  2   7   bad
2  3   8   avg
3  4   9  aavg
4  5  10  vbad

In [157]:
m_Frame.sort_values('cc')

x   y    cc
3  4   9  aavg
2  3   8   avg
1  2   7   bad
0  1   6   gud
4  5  10  vbad

In [158]:
m_Frame.groupby("cc").size()

cc
aavg    1
avg     1
bad     1
gud     1
vbad    1
dtype: int64

## reading data

In [1]:
import pandas as pd
df=pd.read_table("sample.txt")
df

C:\Users\kvsw\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  


Empty DataFrame
Columns: [hai lucky how are you]
Index: []

In [3]:
f=pd.read_table("ex1.csv",sep=',')
f

C:\Users\kvsw\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo